# Generated by Django 3.0.5 on 2020-05-03 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField(default=0)),
                ('room_count', models.IntegerField()),
                ('room_type', models.CharField(choices=[('ST', 'Studio'), ('AP', 'Apartment')], max_length=2)),
                ('beds_number', models.IntegerField(default=1)),
                ('price', models.FloatField()),
                ('reserved_from', models.DateTimeField()),
                ('reserved_until', models.DateTimeField()),
                ('smoking_allowed', models.BooleanField(default=False)),
                ('people_with_disabilities_adapted', models.BooleanField(default=False)),
                ('terrace', models.BooleanField(default=False)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
                ('sound_isolation', models.BooleanField(default=False)),
                ('heating', models.BooleanField(default=False)),
                ('kitchen', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_collections', to='Hotel.Hotel')),
            ],
            options={
                'ordering': ['floor_number'],
            },
        ),
    ]
