# Generated by Django 3.0.5 on 2020-04-30 00:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Hotel', '0002_hotel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.TextField()),
                ('bed_numbers', models.IntegerField(default=1)),
                ('floor_number', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('smoking_allowed', models.BooleanField(default=False)),
                ('people_with_disabilities_adapted', models.BooleanField(default=False)),
                ('room_numbers', models.CharField(blank=True, max_length=240, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_collections', to='Hotel.Hotel')),
            ],
            options={
                'ordering': ['floor_number'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.TextField()),
                ('bed_numbers', models.IntegerField(default=1)),
                ('floor_number', models.IntegerField(default=0)),
                ('price', models.FloatField()),
                ('smoking_allowed', models.BooleanField(default=False)),
                ('people_with_disabilities_adapted', models.BooleanField(default=False)),
                ('room_number', models.IntegerField(default=0)),
                ('room_size', models.TextField()),
                ('terrace', models.BooleanField(default=False)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
                ('sound_isolation', models.BooleanField(default=False)),
                ('heating', models.BooleanField(default=False)),
                ('kitchen', models.BooleanField(default=False)),
                ('room_hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_rooms', to='Hotel.Hotel')),
            ],
            options={
                'ordering': ['floor_number'],
            },
        ),
    ]
