# Generated by Django 3.0.5 on 2020-05-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='price',
            new_name='price_per_adult',
        ),
        migrations.AddField(
            model_name='room',
            name='price_per_child',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
