# Generated by Django 3.0.5 on 2020-04-30 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_hotel',
            new_name='hotel',
        ),
    ]
