# Generated by Django 3.0.5 on 2020-05-02 09:34

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0002_auto_20200430_0341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['room_number', 'floor_number']},
        ),
        migrations.RemoveField(
            model_name='room',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_size',
        ),
        migrations.RemoveField(
            model_name='roomcollection',
            name='choice',
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('ST', 'Studio'), ('AP', 'Apartment')], default='ST', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomcollection',
            name='air_conditioning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomcollection',
            name='heating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomcollection',
            name='kitchen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomcollection',
            name='room_type',
            field=models.CharField(choices=[('ST', 'Studio'), ('AP', 'Apartment')], default='ST', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomcollection',
            name='sound_isolation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomcollection',
            name='terrace',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomcollection',
            name='tv',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='roomcollection',
            name='room_numbers',
            field=models.CharField(default='1', max_length=240, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
            preserve_default=False,
        ),
    ]
