# Generated by Django 3.0.5 on 2020-05-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0003_auto_20200503_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price_per_adult',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_child',
            field=models.FloatField(),
        ),
    ]
