# Generated by Django 3.0.5 on 2020-05-12 11:06

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accommodation', '0007_auto_20200512_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrangement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('reserved_from', models.DateField(default=datetime.date.today)),
                ('reserved_until', models.DateField(default=datetime.date.today)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrangements', to='Accommodation.Accommodation')),
            ],
            options={
                'ordering': ['quantity'],
            },
        ),
    ]
