# Generated by Django 3.0.5 on 2020-04-23 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Arrangement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='arrangement',
            options={'ordering': ['number_of_people']},
        ),
        migrations.RenameField(
            model_name='arrangement',
            old_name='numberOfPeople',
            new_name='number_of_people',
        ),
    ]
