# Generated by Django 3.0.5 on 2020-04-30 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Arrangement', '0002_arrangement_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrangement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrangements', to=settings.AUTH_USER_MODEL),
        ),
    ]
