# Generated by Django 3.0.5 on 2020-05-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accommodation', '0002_auto_20200503_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='reserved_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='reserved_until',
            field=models.DateField(),
        ),
    ]
