# Generated by Django 3.0.5 on 2020-05-10 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
        ('Accommodation', '0005_auto_20200509_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='Hotel.Hotel'),
        ),
    ]
