# Generated by Django 3.0.5 on 2020-05-12 10:27

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('Accommodation', '0006_auto_20200510_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='floor_number',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='floors',
            field=models.CharField(default='1', max_length=83, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
            preserve_default=False,
        ),
    ]
