# Generated by Django 3.0.5 on 2020-05-12 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accommodation', '0007_auto_20200512_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='reserved_from',
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='reserved_until',
        ),
    ]
