# Generated by Django 3.0.5 on 2020-04-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=123456, max_length=10, verbose_name='phone number'),
            preserve_default=False,
        ),
    ]
