# Generated by Django 3.0.5 on 2020-04-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='address', max_length=30, verbose_name='address'),
            preserve_default=False,
        ),
    ]
