# Generated by Django 3.0.5 on 2020-04-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='', max_length=30, verbose_name='city name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(default='company', max_length=30, verbose_name='company name'),
            preserve_default=False,
        ),
    ]
