# Generated by Django 3.0.5 on 2020-04-20 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20200419_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteUser',
            fields=[
                ('city', models.CharField(max_length=30, verbose_name='city name')),
                ('address', models.CharField(max_length=30, verbose_name='address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
    ]
