# Generated by Django 3.0.5 on 2020-04-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20200420_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='address', max_length=30, verbose_name='address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='city', max_length=30, verbose_name='city name'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CompleteUser',
        ),
    ]
