# Generated by Django 3.0.5 on 2020-04-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=30)),
                ('phone', models.CharField(default='111111', max_length=10)),
                ('pib', models.TextField(default='1111111111', max_length=15)),
                ('city', models.TextField(default='city', max_length=30)),
                ('address', models.TextField(default='address', max_length=30)),
            ],
            options={
                'ordering': ['city'],
            },
        ),
    ]
