# Generated by Django 3.0.5 on 2020-04-26 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pib', models.TextField(default='1111111111', max_length=15)),
                ('city', models.TextField(default='city', max_length=30)),
                ('address', models.TextField(default='address', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company'
                                              , to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['city'],
            },
        ),
    ]
