# Generated by Django 3.0.5 on 2020-05-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_companyuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyuser',
            name='address',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='city',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='companyuser',
            name='pib',
            field=models.TextField(max_length=15),
        ),
    ]
