# Generated by Django 3.0.5 on 2020-04-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('city', models.TextField(max_length=50)),
                ('address', models.TextField(max_length=50)),
                ('web_site', models.TextField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('free_parking', models.BooleanField(default=False)),
                ('free_wifi', models.BooleanField(default=False)),
                ('breakfast', models.BooleanField(default=False)),
                ('swimming_pool', models.BooleanField(default=False)),
                ('spa', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['address'],
            },
        ),
    ]
