# Generated by Django 3.0.5 on 2020-05-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='position',
            field=models.IntegerField(choices=[(1, 'Inner_center'), (2, 'Outer_center'), (3, 'Near_airport'), (4, 'Peripheral'), (5, 'Near_sports_center')], default=1),
            preserve_default=False,
        ),
    ]
