# Generated by Django 3.0.5 on 2020-05-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_hotel_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='position',
            field=models.IntegerField(choices=[(1, 'Inner center'), (2, 'Outer center'), (3, 'Near airport'), (4, 'Peripheral'), (5, 'Near sports center')]),
        ),
    ]
