# Generated by Django 3.0.5 on 2020-04-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_auto_20200423_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='name',
            field=models.TextField(default='hotel_name', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.TextField(default='hotel_address', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.TextField(default='hotel_city', max_length=50),
            preserve_default=False,
        ),
    ]
