# Generated by Django 3.0.5 on 2020-04-23 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0004_auto_20200423_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='webSite',
            new_name='web_site',
        ),
    ]
